# Import all queries from their respective modules
from pysmashgg.t_queries import (
    SHOW_QUERY,
    SHOW_WITH_BRACKETS_QUERY,
    SHOW_PLAYERS_BY_SPONSOR,
    SHOW_BY_OWNER_QUERY,
    TOURNAMENT_OWNER_QUERY
)

from pysmashgg.e_queries import (
    EVENT_ID_QUERY,
    SHOW_EVENTS_QUERY,
    SHOW_SETS_QUERY,
    SHOW_ENTRANTS_QUERY,
    SHOW_EVENT_BRACKETS_QUERY,
    SHOW_ENTRANT_SETS_QUERY,
    SHOW_LIGHTWEIGHT_RESULTS_QUERY,
    PLAYER_ID_QUERY,
    ENTRANT_ID_QUERY
)

from pysmashgg.game_queries import (
    GET_VIDEOGAME_ID_QUERY,
    SHOW_BY_VIDEOGAME_QUERY,
    SHOW_EVENT_BY_GAME_SIZE_DATED_QUERY
)

from pysmashgg.location_queries import (
    SHOW_BY_COUNTRY_QUERY,
    SHOW_BY_STATE_QUERY,
    SHOW_BY_RADIUS_QUERY
)

from pysmashgg.p_queries import (
    PLAYER_RECENT_PLACEMENTS_QUERY,
    PLAYER_LOOKUP_ID_QUERY,
    PLAYER_SETS_QUERY,
    PLAYER_INFO_QUERY,
    PLAYER_BY_SLUG_QUERY,
    PLAYER_SHOW_INFO_QUERY,
    PLAYER_SHOW_TOURNAMENTS_QUERY,
    PLAYER_SHOW_TOURNAMENTS_FOR_GAME_QUERY
)

from pysmashgg.b_queries import (
    BRACKET_SHOW_ENTRANTS_QUERY,
    BRACKET_SHOW_SETS_QUERY
)

from pysmashgg.l_queries import (
    SHOW_QUERY as LEAGUE_SHOW_QUERY,
    SHOW_SCHEDULE_QUERY as LEAGUE_SHOW_SCHEDULE_QUERY,
    SHOW_STANDINGS_QUERY as LEAGUE_SHOW_STANDINGS_QUERY
)

# Export all queries
__all__ = [
    # Tournament queries
    'SHOW_QUERY',
    'SHOW_WITH_BRACKETS_QUERY',
    'SHOW_PLAYERS_BY_SPONSOR',
    'SHOW_BY_OWNER_QUERY',
    'TOURNAMENT_OWNER_QUERY',

    # Event queries
    'EVENT_ID_QUERY',
    'SHOW_EVENTS_QUERY',
    'SHOW_SETS_QUERY',
    'SHOW_ENTRANTS_QUERY',
    'SHOW_EVENT_BRACKETS_QUERY',
    'SHOW_ENTRANT_SETS_QUERY',
    'SHOW_LIGHTWEIGHT_RESULTS_QUERY',
    'PLAYER_ID_QUERY',
    'ENTRANT_ID_QUERY',

    # Game queries
    'GET_VIDEOGAME_ID_QUERY',
    'SHOW_BY_VIDEOGAME_QUERY',
    'SHOW_EVENT_BY_GAME_SIZE_DATED_QUERY',

    # Location queries
    'SHOW_BY_COUNTRY_QUERY',
    'SHOW_BY_STATE_QUERY',
    'SHOW_BY_RADIUS_QUERY',

    # Player queries
    'PLAYER_RECENT_PLACEMENTS_QUERY',
    'PLAYER_LOOKUP_ID_QUERY',
    'PLAYER_SETS_QUERY',
    'PLAYER_INFO_QUERY',
    'PLAYER_BY_SLUG_QUERY',
    'PLAYER_SHOW_INFO_QUERY',
    'PLAYER_SHOW_TOURNAMENTS_QUERY',
    'PLAYER_SHOW_TOURNAMENTS_FOR_GAME_QUERY',

    # Bracket queries
    'BRACKET_SHOW_ENTRANTS_QUERY',
    'BRACKET_SHOW_SETS_QUERY',

    # League queries
    'LEAGUE_SHOW_QUERY',
    'LEAGUE_SHOW_SCHEDULE_QUERY',
    'LEAGUE_SHOW_STANDINGS_QUERY'
]
